create database DU_AN_1
GO
USE DU_AN_1
GO
--NHÂN VIÊN--
CREATE TABLE NhanVien(
IDNV UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
MANV VARCHAR(100) UNIQUE,
HoVaTen NVARCHAR(100) ,
GioiTinh INT,
NgaySinh DATE,
DiaChi NVARCHAR(100),
Sdt VARCHAR(100),
ChucVu INT DEFAULT 0,
MatKhau VARCHAR(50) NOT NULL,
HinhAnh varchar(100),
TrangThai INT DEFAULT 0,
)
GO
create TABLE KhachHang(
IDKH UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma varchar(100) unique,
SDT VARCHAR(100) unique ,
HOTEN NVARCHAR(100),
GIOITINH INT,
DiaChi  NVARCHAR(100)
)
GO
CREATE TABLE HOA_DON(
ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IDNV UNIQUEIDENTIFIER,
IDKH UNIQUEIDENTIFIER,
MA VARCHAR(100) UNIQUE,
NGAY_TAO DATE,
NGAY_THANH_TOAN DATE,
TINH_TRANG INT DEFAULT 0,
MO_TA NVARCHAR(100),
)
GO
CREATE TABLE HOA_DON_CT(
ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
ID_CTSP UNIQUEIDENTIFIER,
ID_HOA_DON UNIQUEIDENTIFIER,
ID_DMK UNIQUEIDENTIFIER,
ID_PBH UNIQUEIDENTIFIER,
SO_LUONG INT,
DON_GIA DECIMAL(20,0) DEFAULT 0,
)
GO
CREATE TABLE DON_GIAO(
ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
ID_HOA_DON UNIQUEIDENTIFIER,
NGUOI_NHAN NVARCHAR(100),
SDT_NN VARCHAR(10),
NGUOI_GIAO NVARCHAR(100),
SDT_NG VARCHAR(10),
DIA_CHI NVARCHAR(100),
NGAY_DAO DATE,
NGAY_NHAN DATE,
TINH_TRANG INT DEFAULT 0,
)
GO
Create TABLE DotKhuyenMai(
ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IDNV  UNIQUEIDENTIFIER,
IDCTSP UNIQUEIDENTIFIER,
LoaiMa NVARCHAR(100),
MaVoucher VARCHAR(100),
GiaTri DECIMAL(20,0) DEFAULT 0,
TenKhuyenMai nvarchar(100) not null,
NgayBatDau date,
NgayketThuc date,
trangthai int
)
GO
CREATE TABLE PhieuBaoHanh(
IDPBH UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
idGoiBaoHanh UNIQUEIDENTIFIER,
IDHD UNIQUEIDENTIFIER,
TenKhachHang nvarchar(100),
NgayBatDau DATE,
NGayKetThuc DATE,
TrangThai int,
DiaChi NVARCHAR(100),
SdtCH VARCHAR(10),
Mota VARCHAR(1000),
)


create table GoiBaoHanh(
id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
ten nvarchar(100),
TrangThai int
)

GO
-- SẢN PHẨM--
CREATE TABLE SanPham(
ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(100) UNIQUE,
Ten VARCHAR(100) NOT NULL,
TinhTrang int default 0
)
GO
CREATE TABLE HeDieuHanh(
ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(100) UNIQUE,
Ten VARCHAR(100) NOT NULL,
TinhTrang int default 0
)
GO
CREATE TABLE Hang(
ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(100) UNIQUE,
Ten VARCHAR(100) NOT NULL,
TinhTrang int default 0
)
GO
CREATE TABLE DongSP(
ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(100) UNIQUE,
Ten VARCHAR(100) NOT NULL,
TinhTrang int default 0
)
GO
CREATE TABLE Rom(
ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(100) UNIQUE,
DUNGLUONG VARCHAR(100) NOT NULL,
TinhTrang int default 0
)
GO
CREATE TABLE Ram(
ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
MA VARCHAR(100) UNIQUE,
DUNGLUONG VARCHAR(100) NOT NULL,
TinhTrang int default 0
)
GO
CREATE TABLE MauSac(
ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(100) UNIQUE,
Ten VARCHAR(100) NOT NULL,
TinhTrang int default 0
)
GO
CREATE TABLE ManHinh(
ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(100) UNIQUE,
Ten VARCHAR(100) NOT NULL,
TinhTrang int default 0
)
GO
CREATE TABLE Pin(
ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(100) UNIQUE,
DungLuong VARCHAR(100) NOT null,
TinhTrang int default 0
)
go
CREATE TABLE CPU(
ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(100) UNIQUE,
Ten Nvarchar(100),
TinhTrang int default 0
)
CREATE TABLE Imei(
ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IDCTSP UNIQUEIDENTIFIER,
SO_Imei VARCHAR(100) UNIQUE NOT NULL,
TinhTrang int default 0
)

GO
CREATE TABLE CHiTietSP(
ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IDSP  UNIQUEIDENTIFIER,
IDHDH   UNIQUEIDENTIFIER,
IDHNG  UNIQUEIDENTIFIER,
IDDongSP UNIQUEIDENTIFIER,
IDCPU UNIQUEIDENTIFIER,
IDRom UNIQUEIDENTIFIER,
IDRam UNIQUEIDENTIFIER,
IDMS  UNIQUEIDENTIFIER,
IDMH  UNIQUEIDENTIFIER,
IDPin  UNIQUEIDENTIFIER,
Loai INT DEFAULT 0,
SoLuong int default 0,
HinhAnh varchar(100),
GiaNhap DECIMAL(20,0) DEFAULT 0,
GiaBan DECIMAL(20,0) DEFAULT 0,
TinhTrang int default 0
)
alter table CHiTietSP
add MaSSP varchar(100) unique
----MOI QUA HE----
ALTER TABLE CHITIETSP
ADD CONSTRAINT  FK1 FOREIGN KEY (IDSP) REFERENCES SANPHAM(ID)
GO
ALTER TABLE CHITIETSP
ADD CONSTRAINT  FK2 FOREIGN KEY (IDHDH) REFERENCES HEDIEUHANH(ID)
GO
ALTER TABLE CHITIETSP
ADD CONSTRAINT  FK3 FOREIGN KEY (IDHNG) REFERENCES HANG(ID)
GO
ALTER TABLE CHITIETSP
ADD CONSTRAINT  FK4 FOREIGN KEY (IDDONGSP) REFERENCES DONGSP(ID)
GO
ALTER TABLE CHITIETSP
ADD CONSTRAINT  FK5 FOREIGN KEY (IDROM) REFERENCES ROM(ID)
GO
ALTER TABLE CHITIETSP
ADD CONSTRAINT  FK6 FOREIGN KEY (IDRAM) REFERENCES RAM(ID)
GO
ALTER TABLE CHITIETSP
ADD CONSTRAINT  FK7 FOREIGN KEY (IDMH) REFERENCES ManHinh(ID)
GO
ALTER TABLE CHITIETSP
ADD CONSTRAINT  FK8 FOREIGN KEY (IDPIN) REFERENCES PIN(ID)
GO
ALTER TABLE CHITIETSP
ADD CONSTRAINT  FK9 FOREIGN KEY (IDCPU) REFERENCES CPU(ID)
GO
ALTER TABLE CHITIETSP
ADD CONSTRAINT  FK10 FOREIGN KEY (IDMS) REFERENCES MAUSAC(ID)
GO
ALTER TABLE Imei
add CONSTRAINT FK11 FOREIGN KEY (IDCTSP) REFERENCES ChiTietSP(ID)
GO

ALTER TABLE HOA_DON
ADD CONSTRAINT FK12 FOREIGN KEY (IDNV) REFERENCES NhanVien(IDNV)
go

ALTER TABLE HOA_DON
add CONSTRAINT FK13 FOREIGN KEY (IDKH) REFERENCES khachhang(IDKH)
GO
ALTER TABLE HOA_DON_CT
ADD CONSTRAINT FK14 FOREIGN KEY (ID_HOA_DON) REFERENCES HOA_DON(ID)
go

ALTER TABLE DON_GIAO
ADD CONSTRAINT FK16 FOREIGN KEY (ID_HOA_DON) REFERENCES HOA_DON(ID)
GO
ALTER TABLE DotKhuyenMai
ADD CONSTRAINT FK18 FOREIGN KEY (IDNV) REFERENCES NhanVien(IDNV)
go


ALTER TABLE PhieuBaoHanh
ADD CONSTRAINT FK20 FOREIGN KEY (IDHD) REFERENCES HOA_DON(ID)
GO
ALTER TABLE PhieuBaoHanh
ADD CONSTRAINT FK21 FOREIGN KEY (idGoiBaoHanh) REFERENCES GoiBaoHanh(ID)
GO

ALTER TABLE HOA_DON_CT
ADD CONSTRAINT FK23 FOREIGN KEY (ID_DMK) REFERENCES DotKhuyenMai(ID)
go
ALTER TABLE HOA_DON_CT
ADD CONSTRAINT FK24 FOREIGN KEY (ID_PBH) REFERENCES PhieuBaoHanh(IDPBH)
go
ALTER TABLE HOA_DON_CT
ADD CONSTRAINT FK25 FOREIGN KEY (ID_CTSP) REFERENCES CHiTietSP(ID)
GO

